//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PSSCEntities : DbContext
    {
        public PSSCEntities()
            : base("name=PSSCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Proffessor> Proffessors { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Studentt> Studentts { get; set; }
    
        public virtual ObjectResult<proc_materii_Result> proc_materii()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_materii_Result>("proc_materii");
        }
    
        public virtual ObjectResult<select_Stud_Result> select_Stud()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_Stud_Result>("select_Stud");
        }
    }
}
