//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    using Common.Common;

    public partial class Studentt:IEntity
    {
        public string Nume { get; set; }
        public int Credite { get; set; }
        public string Numar_matricol { get; set; }
    }
}
